### ISSUE TITLE
[QUESTION] Cropper Data

### ISSUE THREAD

**Issue by angelru** [CropperBlazor/Cropper.Blazor#101]
Is there a way to lock the Cropper Data so that the height and width cannot be modified and stay fixed?

`CropBoxResizable `not working?

**Comment by MaxymGorn** [comment]
Hi @angelru !  Well, good question! I'll see if this original JS library (https://github.com/fengyuanchen/cropperjs) supports this solution!

**Comment by MaxymGorn** [comment]
Yes, it does not work in our library - BUG, since the functionality of transferring all options to the cropper has not yet been fully tested.

The main problem is when used that we don't pass a default value for CropBoxResizable (Options class) and other changes
<img width="482" alt="image" src="https://user-images.githubusercontent.com/50423072/202826578-2fbc0d05-8cf5-48b2-ab80-def3dceed347.png">

Solution Since this is a required parameter, we should always pass it:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/50423072/202826727-b9f7e5a7-30da-46f3-a451-5b4e8eff6697.png">

**Comment by angelru** [comment]
I understand, is that I can not set a height and width at the beginning and also disable the resizing of the box.

**Comment by MaxymGorn** [comment]
Maybe you want that work the same as that project: https://avatarcropper.com/ ?

**Comment by MaxymGorn** [comment]
You can also disable dragging at the beginning by enabling DragMode.Move now!

**Comment by angelru** [comment]
thanks

**Comment by MaxymGorn** [comment]
Hi @angelru ! We will update the version of the package with a fix for passing options for Cropper.js: https://github.com/CropperBlazor/Cropper.Blazor/pull/102

**Comment by MaxymGorn** [comment]
Also I found a way to set the width (200 )and height (100) to be fixed initially, here is a sample configuration
<img width="329" alt="image" src="https://user-images.githubusercontent.com/50423072/203818088-f485ac8c-8d94-411a-8964-773c8f73f07a.png">

**Comment by MaxymGorn** [comment]
Sorry for taking so long, because in Ukraine we have very big problems with electricity

**Comment by angelru** [comment]
Thanks!!!Much encouragement and strength to you, your loved ones and to Ukraine!

**Comment by MaxymGorn** [comment]
Thanks!

**Comment by MaxymGorn** [comment]
@angelru Released NuGet package version 1.1.1: https://www.nuget.org/packages/Cropper.Blazor
